# Generated by Django 5.2.10 on 2026-01-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del perfil')),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción del perfil')),
                ('perfilactivo', models.IntegerField(blank=True, null=True, verbose_name='Perfil activo')),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True, verbose_name='Apellidos')),
                ('nombres', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombres')),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidad')),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar de nacimiento')),
                ('fechanacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('numerocedula', models.CharField(max_length=10, unique=True, verbose_name='Número de cédula')),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True, verbose_name='Sexo')),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado civil')),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True, verbose_name='Licencia de conducir')),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono convencional')),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono fijo')),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección de trabajo')),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección domiciliaria')),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sitio web')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Datos personales',
                'verbose_name_plural': 'Datos personales',
                'db_table': 'datospersonales',
            },
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID curso realizado')),
                ('nombrecurso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del curso')),
                ('fechainicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fechafin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('totalhoras', models.IntegerField(blank=True, null=True, verbose_name='Total de horas')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la hoja de vida')),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta del certificado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='hojavida.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Curso realizado',
                'verbose_name_plural': 'Cursos realizados',
                'db_table': 'cursosrealizados',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencilaboral', models.AutoField(primary_key=True, serialize=False, verbose_name='ID experiencia laboral')),
                ('cargodesempenado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo desempeñado')),
                ('nombrempresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la empresa')),
                ('fechainiciogestion', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fechafingestion', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción de funciones')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la hoja de vida')),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta del certificado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='hojavida.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
                'db_table': 'experiencialaboral',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False, verbose_name='ID producto académico')),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del producto')),
                ('fechaproducto', models.DateField(blank=True, null=True, verbose_name='Fecha del producto')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la hoja de vida')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='hojavida.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Producto académico',
                'verbose_name_plural': 'Productos académicos',
                'db_table': 'productosacademicos',
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False, verbose_name='ID producto laboral')),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del producto')),
                ('fechaproducto', models.DateField(blank=True, null=True, verbose_name='Fecha del producto')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la hoja de vida')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='hojavida.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Producto laboral',
                'verbose_name_plural': 'Productos laborales',
                'db_table': 'productoslaborales',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID reconocimiento')),
                ('tiporeconocimiento', models.CharField(blank=True, choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100, null=True, verbose_name='Tipo de reconocimiento')),
                ('fechareconocimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de reconocimiento')),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('institucioncertificado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Institución del certificado')),
                ('fotocertificado', models.ImageField(blank=True, null=True, upload_to='certificados/reconocimientos/', verbose_name='Foto del certificado')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la hoja de vida')),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta del certificado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='hojavida.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'db_table': 'reconocimientos',
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False, verbose_name='ID venta garage')),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del producto')),
                ('estadoproducto', models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, null=True, verbose_name='Estado del producto')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor del bien')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la hoja de vida')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='hojavida.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Venta garage',
                'verbose_name_plural': 'Venta garage',
                'db_table': 'ventagarage',
            },
        ),
    ]
