# Generated by Django 6.0.1 on 2026-01-28 03:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilactivo', models.IntegerField(blank=True, default=1, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
                ('nombres', models.CharField(blank=True, max_length=60, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('numerocedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='sexo', max_length=1, null=True, verbose_name='Sexo')),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], db_column='licenciaconducir', max_length=10, null=True, verbose_name='¿Tiene licencia de conducir?')),
                ('telefonoconvencional', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('telefonofijo', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
                'db_table': 'datospersonales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.ImageField(blank=True, null=True, upload_to='cursos_certificados/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
            options={
                'db_table': 'cursosrealizados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('fechainiciogestion', models.DateField(blank=True, null=True)),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_laborales/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
            options={
                'db_table': 'experiencialaboral',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos_academicos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
            options={
                'db_table': 'productosacademicos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos_laborales/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
            options={
                'db_table': 'productoslaborales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fechareconocimiento', models.DateField(blank=True, null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('institucioncertificado', models.CharField(blank=True, max_length=150, null=True)),
                ('fotocertificado', models.ImageField(blank=True, null=True, upload_to='reconocimientos_fotos/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='reconocimientos_docs/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
            options={
                'db_table': 'reconocimientos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoproducto', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojavida.datospersonales')),
            ],
            options={
                'db_table': 'ventagarage',
                'managed': True,
            },
        ),
    ]
