# Generated by Django 6.0.1 on 2026-01-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='idexperiencilaboral',
            new_name='idexperiencialaboral',
        ),
    ]
