# Generated by Django 6.0.1 on 2026-01-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0002_rename_idexperiencilaboral_experiencialaboral_idexperiencialaboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.ImageField(blank=True, null=True, upload_to='cursos_certificados/')),
            ],
            options={
                'db_table': 'cursosrealizados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos_academicos/')),
            ],
            options={
                'db_table': 'productosacademicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos_laborales/')),
            ],
            options={
                'db_table': 'productoslaborales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fechareconocimiento', models.DateField(blank=True, null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('institucioncertificado', models.CharField(blank=True, max_length=150, null=True)),
                ('fotocertificado', models.ImageField(blank=True, null=True, upload_to='reconocimientos_fotos/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='reconocimientos_docs/')),
            ],
            options={
                'db_table': 'reconocimientos',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='perfil',
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'managed': False, 'verbose_name': 'Datos Personales', 'verbose_name_plural': 'Datos Personales'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='CursoRealizado',
        ),
        migrations.DeleteModel(
            name='ProductoAcademico',
        ),
        migrations.DeleteModel(
            name='ProductoLaboral',
        ),
        migrations.DeleteModel(
            name='Reconocimiento',
        ),
    ]
