# Generated by Django 6.0.1 on 2026-01-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0003_cursosrealizados_productosacademicos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'managed': True, 'verbose_name': 'Datos Personales', 'verbose_name_plural': 'Datos Personales'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'managed': True},
        ),
    ]
